# Generated by Django 3.0.4 on 2020-04-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0002_auto_20200404_2123'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advicestouser',
            unique_together={('user', 'advice')},
        ),
    ]
