# Generated by Django 3.0.3 on 2020-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200226_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='actual_goal_weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
