# Generated by Django 3.0.3 on 2020-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0006_remove_robotadvices_advices_to_user'),
        ('account', '0003_profileuser_actual_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityuser',
            name='advices_to_user',
            field=models.ManyToManyField(to='dietetic.RobotAdvices'),
        ),
    ]
