# Generated by Django 3.0.3 on 2020-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_identityuser_advices_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyuser',
            name='start_questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
