# Generated by Django 3.0.3 on 2020-03-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_historyuser_start_questionnaire_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsuser',
            name='weighing_date',
            field=models.DateField(default=datetime.date.today, null=True, unique=True),
        ),
    ]
