# Generated by Django 3.0.3 on 2020-03-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200308_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultsuser',
            unique_together={('user', 'weighing_date')},
        ),
    ]
