# Generated by Django 3.0.4 on 2020-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200309_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='identityuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
