# Generated by Django 3.0.4 on 2020-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200324_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='identityuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
