# Generated by Django 3.0.4 on 2020-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0010_auto_20200324_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='identityuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
