# Generated by Django 3.0.4 on 2020-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0011_auto_20200324_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='identityuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='statususer',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='statususer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='statususer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
