language: python
python:
  - "3.7"

env :
  - DJANGO_SETTINGS_MODULE='dietetic_project.settings.travis'

addons:
  postgresql: "9.4"
services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py migrate
  - python manage.py loaddata data.json
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export MOZ_HEADLESS=1
  - python manage.py test

branches:
  only:
    - master
    - develop1
