language: python
python:
  - "3.7"

env :
  - DJANGO_SETTINGS_MODULE='dietetic_project.settings.travis'

addons:
  postgresql: "9.4"
services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - export LC_ALL="fr_FR.UTF-8"
  - export LC_CTYPE="fr_FR.UTF-8"
  - sudo dpkg-reconfigure locales
  - python manage.py migrate
  - python manage.py loaddata data.json
  - python manage.py test

branches:
  only:
    - master

