# Generated by Django 3.0.3 on 2020-02-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotAdvices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, unique=True)),
                ('advices_to_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobotAdviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, null=True)),
                ('robot_advices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdvices')),
            ],
        ),
        migrations.CreateModel(
            name='RobotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotQuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True, unique=True)),
                ('discussion_space', models.ManyToManyField(through='dietetic.RobotAnswer', to='dietetic.RobotQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='robotquestion',
            name='robot_question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestionType'),
        ),
        migrations.AddField(
            model_name='robotanswer',
            name='robot_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestion'),
        ),
        migrations.AddField(
            model_name='robotanswer',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.UserAnswer'),
        ),
        migrations.AddField(
            model_name='robotadvices',
            name='robot_advice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdviceType'),
        ),
    ]
