# Generated by Django 3.0.4 on 2020-04-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_answer', models.CharField(max_length=700, null=True, verbose_name='réponse du robot')),
            ],
            options={
                'verbose_name': 'Echange',
            },
        ),
        migrations.CreateModel(
            name='RobotAdviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True, verbose_name='type de conseil')),
            ],
            options={
                'verbose_name': 'Type de conseil',
            },
        ),
        migrations.CreateModel(
            name='RobotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700, unique=True, verbose_name='question du robot')),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='RobotQuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True, verbose_name='type de question')),
            ],
            options={
                'verbose_name': 'Type de question',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True, unique=True, verbose_name="réponse de l'utilisateur")),
                ('discussion_space', models.ManyToManyField(through='dietetic.DiscussionSpace', to='dietetic.RobotQuestion')),
            ],
            options={
                'verbose_name': 'Réponse',
            },
        ),
        migrations.AddField(
            model_name='robotquestion',
            name='robot_question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestionType', verbose_name='type de question'),
        ),
        migrations.CreateModel(
            name='RobotAdvices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1700, unique=True, verbose_name='conseil du robot')),
                ('robot_advice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdviceType', verbose_name='type de conseil')),
            ],
            options={
                'verbose_name': 'Conseil',
            },
        ),
        migrations.AddField(
            model_name='discussionspace',
            name='robot_advices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdvices', verbose_name='conseil du robot'),
        ),
        migrations.AddField(
            model_name='discussionspace',
            name='robot_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestion', verbose_name='question du robot'),
        ),
        migrations.AddField(
            model_name='discussionspace',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.UserAnswer', verbose_name="réponse de l'utilisateur"),
        ),
    ]
