# Generated by Django 3.0.4 on 2020-04-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionspace',
            unique_together={('user_answer', 'robot_question')},
        ),
    ]
