# Generated by Django 3.0.3 on 2020-02-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0002_auto_20200220_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionspace',
            old_name='text',
            new_name='robot_answer',
        ),
    ]
