# Generated by Django 3.0.3 on 2020-03-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0003_auto_20200220_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionspace',
            name='robot_advices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdvices'),
        ),
        migrations.AlterField(
            model_name='discussionspace',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.UserAnswer'),
        ),
    ]
