# Generated by Django 3.0.3 on 2020-03-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0011_auto_20200303_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionspace',
            unique_together={('user_answer', 'robot_question')},
        ),
    ]
