# Generated by Django 3.0.3 on 2020-03-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0012_auto_20200305_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussionspace',
            unique_together=set(),
        ),
    ]
