# Generated by Django 3.0.4 on 2020-04-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0014_auto_20200305_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionspace',
            options={'verbose_name': 'Echange'},
        ),
        migrations.AlterModelOptions(
            name='robotadvices',
            options={'verbose_name': 'Conseil'},
        ),
        migrations.AlterModelOptions(
            name='robotadvicetype',
            options={'verbose_name': 'Type de conseil'},
        ),
        migrations.AlterModelOptions(
            name='robotquestion',
            options={'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='robotquestiontype',
            options={'verbose_name': 'Type de question'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Réponse'},
        ),
        migrations.AlterField(
            model_name='discussionspace',
            name='robot_advices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdvices', verbose_name='conseil du robot'),
        ),
        migrations.AlterField(
            model_name='discussionspace',
            name='robot_answer',
            field=models.CharField(max_length=700, null=True, verbose_name='réponse du robot'),
        ),
        migrations.AlterField(
            model_name='discussionspace',
            name='robot_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestion', verbose_name='question du robot'),
        ),
        migrations.AlterField(
            model_name='discussionspace',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietetic.UserAnswer', verbose_name="réponse de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='robotadvices',
            name='robot_advice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotAdviceType', verbose_name='type de conseil'),
        ),
        migrations.AlterField(
            model_name='robotadvices',
            name='text',
            field=models.CharField(max_length=1700, unique=True, verbose_name='conseil du robot'),
        ),
        migrations.AlterField(
            model_name='robotadvicetype',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='type de conseil'),
        ),
        migrations.AlterField(
            model_name='robotquestion',
            name='robot_question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietetic.RobotQuestionType', verbose_name='type de question'),
        ),
        migrations.AlterField(
            model_name='robotquestion',
            name='text',
            field=models.CharField(max_length=700, unique=True, verbose_name='question du robot'),
        ),
        migrations.AlterField(
            model_name='robotquestiontype',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='type de question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name="réponse de l'utilisateur"),
        ),
        migrations.AlterUniqueTogether(
            name='discussionspace',
            unique_together=set(),
        ),
    ]
